spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: http://106.13.165.21/
    port: 5672
    username: guest
    password: guest

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
